<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-J2MEAOF0" failures="1" tests="1" name="TestLocal" time="9.206" errors="0" timestamp="2022-12-27T13:26:27 IST">
  <testcase classname="script.Test1" name="testA" time="0.235">
    <failure type="java.lang.AssertionError" message="expected [CONTACT ME] but found [CONTACT US]">
      <![CDATA[java.lang.AssertionError: expected [CONTACT ME] but found [CONTACT US]
at script.Test1.testA(Test1.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testA -->
</testsuite> <!-- TestLocal -->
